const SET_ASSISTANT_NAME = "SET_ASSISTANT_NAME";
const SET_ASSISTANT_GENDER = "SET_ASSISTANT_GENDER";
const SET_SCHEME_COLOR = "SET_SCHEME_COLOR";

export { SET_ASSISTANT_NAME, SET_ASSISTANT_GENDER, SET_SCHEME_COLOR };