const SET_ASSISTANT_NAME = "SET_ASSISTANT_NAME";
const SET_ASSISTANT_GENDER = "SET_ASSISTANT_GENDER";
const SET_SCHEME_COLOR = "SET_SCHEME_COLOR";
const NEXT_STEP = "NEXT_STEP";

export { NEXT_STEP, SET_ASSISTANT_NAME, SET_ASSISTANT_GENDER, SET_SCHEME_COLOR };